--- #YAML:1.0
name:               List-Rotation
version:            1.010
abstract:           Loop (Cycle, Alternate or Toggle) through a list of values via a singleton object implemented as closure.
author:
    - pelagic
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Memoize:     0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
